version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    hostname: mysql
    env_file:
      - "docker.env"
    networks:
      - shelf-network

  shelf:
    build: .
    container_name: shelf
    ports:
      - "8080:8080"
    env_file:
      - "docker.env"
    hostname: shelf
    restart: always
    networks:
      - shelf-network
    depends_on:
      - mysql

networks:
  shelf-network:
    driver: bridge